name: CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Frontend
        working-directory: frontend
        run: npm install

      - name: Install Backend
        working-directory: backend
        run: npm install

      - name: Run Lint
        working-directory: frontend
        run: npm run lint

      - name: Build Frontend
        working-directory: frontend
        run: npm run build

      - name: Build Backend
        working-directory: backend
        run: npm run build
